### ISSUE TITLE
incorrect terra button test routes 

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-site#34]
# Issue Description
When launching terra-site in cerner-consumer-theme, button tests path in `generatedComponentConfig.js` looks like:
```
      {
        name: 'Button',
        path: '/button',
        tests: [
          {
            name: 'Active Variant Buttons',
            path: '/active-variant-buttons',
            component: ActiveVariantButtons,
          },
          {
            name: 'Button Types',
            path: '/button-types',
            component: ButtonTypes,
          },
          {
            name: 'Icon Button',
            path: '/icon-button',
            component: IconButton,
          },
          {
            name: 'Long Text Button',
            path: '/long-text-button',
            component: LongTextButton,
          },
          {
            name: 'Variant Button',
            path: '/variant-button',
            component: VariantButton,
          },
        ],
      },
```
generatedComponentConfig.js assumes a 1 to1 mapping between a test file name and its route. But for button a test file might include multiple test cases, such as ButtonTypes: https://github.com/cerner/terra-core/blob/master/packages/terra-button/tests/nightwatch/ButtonTypes.jsx

The actual test routes are different: https://github.com/cerner/terra-core/blob/master/packages/terra-button/tests/nightwatch/ButtonTestRoutes.jsx

So if navigating to `http://localhost:8080/#/tests/core/button/button-types`, it shows an empty page

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

**Comment by emilyrohrbough** [comment]
This issue will be resolved in https://github.com/cerner/terra-core/issues/1254, and [these test routes](https://github.com/cerner/terra-core/blob/master/packages/terra-button/tests/nightwatch/ButtonTestRoutes.jsx) will no longer be valid.  The one unfortunate side affect of automatically generated configuration we way we currently do means all components examples must be stand-alone files or be rendered within the same example page.

**Comment by emilyrohrbough** [comment]
Linking this issue to https://github.com/cerner/terra-core/blob/master/packages/terra-button/tests/nightwatch/ButtonTestRoutes.jsx to ensure this gets resolved.
